### Create Billing Account

GRPC localhost:9001/BillingService/CreateBillingAccount

{
  "patientId": "8f882639-3921-479b-bef9-911e22d85a7f",
  "name": "hema billijg",
  "email": "hemabill@gmail.com"
}