### updates patient information
PUT http://localhost:4000/patients/604e2dfe-f4c7-4b07-bc19-770cd5d34a65
Content-Type: application/json

{
  "name": "hema",
  "email": "hema37@gmail.com",
  "address": "11 overlea",
  "dateOfBirth": "1996-09-20"
}


